version: 0.2
env:
  variables:
    TF_VERSION: "0.10.7"
phases:
  install:
    commands:
      - pwd
      - ls
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 572872725253.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo $INPUT_ENV
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t acapy .
      - echo "Version--> " `cat version.txt`
      - VERSION=`cat version.txt`
      - docker tag acapy 572872725253.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$INPUT_ENV-acapy:$VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 572872725253.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$INPUT_ENV-acapy:$VERSION
      - sed -i 's/<VERSION>/'$VERSION'/g' taskdef.json
      - sed -i 's/<ENV>/'$INPUT_ENV'/g' taskdef.json
      - sed -i 's/<REGION>/'$AWS_DEFAULT_REGION'/g' taskdef.json
      - echo Writing image definitions file...
      - SERVICE_NAME=$INPUT_ENV"-acapy"
      - printf '[{"name":"%s","imageUri":"%s"}]' $SERVICE_NAME 572872725253.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$INPUT_ENV-acapy:$VERSION > imagedefinitions.json

artifacts:
  files:
    - 'taskdef.json'
    - 'buildspec.yml'
    - 'imagedefinitions.json'
