version: 0.2
env:
  variables:
    TF_VERSION: "0.10.7"
phases:
  install:
    commands:
      - pwd
      - ls
  pre_build:
    commands:
      - pip install --upgrade setuptools
      - pip install --upgrade pip
      - pip install --upgrade wheel
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - sed -i 's/<ACCOUNTID>/'$ACCOUNTID'/g' Dockerfile
      - sed -i 's/<REGION>/'$AWS_DEFAULT_REGION'/g' Dockerfile
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t acapy .
      - echo "Version--> " `cat version.txt`
      - VERSION=`cat version.txt`
      - docker tag acapy $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/acapy:$VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNTID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/acapy:$VERSION
      - sed -i 's/<VERSION>/'$VERSION'/g' taskdef.json
      - sed -i 's/<REGION>/'$AWS_DEFAULT_REGION'/g' taskdef.json
      - sed -i 's/<ACCOUNTID>/'$ACCOUNTID'/g' taskdef.json
      - sed -i 's/<ACAPY_ENDPOINT>/'$ACAPY_ENDPOINT'/g' taskdef.json
      - sed -i 's/<WEBHOOK_ADDRESS>/'$WEBHOOK_ADDRESS'/g' taskdef.json
      - sed -i 's/<RDS_ACAPY_ARN>/'$RDS_ACAPY_ARN'/g' startup.sh
      - sed -i 's/<RDS_ACAPY_USER>/'$RDS_ACAPY_USER'/g' startup.sh
      - sed -i 's/<RDS_ACAPY_PASSWORD>/'$RDS_ACAPY_PASSWORD'/g' startup.sh
      - cat startup.sh
artifacts:
  files:
    - 'taskdef.json'
    - 'buildspec.yml'
    - 'appspec.yml'
