version: "3.9"
services:
  agent-hub:
    build: .
    environment:
      - AGENT_NAME=${AGENT_NAME}
      - PORT=${PORT}
      - ADMIN_PORT=${ADMIN_PORT}
      - WEBHOOK_ADDRESS=${WEBHOOK_ADDRESS}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
     - "3005:3005"
     - "8150:8150"