version: "3"
services:
  tunnel-sophia:
    image: reflectivedevelopment/agent-tunnel
    command: "agent-sophia:3005 -p 4040 --host ${AGENT_TUNNEL_HOST}"
  agent-sophia:
    build: .
    environment:
      TUNNEL_HOST: tunnel-sophia
      AGENT_NAME: Sophia
      PORT: 3005
      ADMINPORT: 8150
    ports:
     - "3005:3005"
     - "8150:8150"

  tunnel-dmv:
    image: reflectivedevelopment/agent-tunnel
    command: "agent-dmv:3006 -p 4040 --host ${AGENT_TUNNEL_HOST}"
  agent-dmv:
    build: .
    environment:
      TUNNEL_HOST: tunnel-dmv
      AGENT_NAME: DMV
      PORT: 3006
      ADMINPORT: 8151
    ports:
     - "3006:3006"
     - "8151:8151"

  tunnel-bank:
    image: reflectivedevelopment/agent-tunnel
    command: "agent-bank:3007 -p 4040 --host ${AGENT_TUNNEL_HOST}"
  agent-bank:
    build: .
    environment:
      TUNNEL_HOST: tunnel-bank
      AGENT_NAME: Bank
      PORT: 3007
      ADMINPORT: 8152
    ports:
     - "3007:3007"
     - "8152:8152"
