version: "3"
services:
  tunnel-inidico-trainer:
    image: reflectivedevelopment/agent-tunnel
    command: "agent-indicio-trainer:3008 -p 4040 --host ${AGENT_TUNNEL_HOST}"
  agent-indicio-trainer:
    build: .
    environment:
      NGROK_NAME: ngrok-indicio-trainer
      TUNNEL_HOST: tunnel-inidico-trainer
      AGENT_NAME: Indicio Trainer
      PORT: 3008
      ADMINPORT: 8154
    ports:
     - "3008:3008"
     - "8154:8154"
