version: "3"
services:
  tunnel-alice:
    image: agent-tunnel
    build: agent-tunnel
    command: agent-alice:3000 -p 4040
  agent-alice:
    image: acapy-toolbox-tunnel
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo
    environment:
      TUNNEL_HOST: tunnel-alice
      TUNNEL_PORT: 4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3001:3001"
    command: poetry run aca-py start --arg-file ./configs/alice.yml

  tunnel-bob:
    image: agent-tunnel
    build: agent-tunnel
    command: agent-bob:3002 -p 4040
  agent-bob:
    image: acapy-toolbox-tunnel
    environment:
      TUNNEL_HOST: tunnel-bob
      TUNNEL_PORT: 4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3003:3003"
    command: poetry run aca-py start --arg-file ./configs/bob.yml 
