version: "3"
services:
  tunnel-alice:
    image: reflectivedevelopment/agent-tunnel
    command: agent-alice:3000 -p 4040 --host ${AGENT_TUNNEL_HOST}
  agent-alice:
    image: acapy-toolbox-tunnel
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo
    environment:
      TUNNEL_HOST: tunnel-alice
      TUNNEL_PORT: 4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3001:3001"
    command: poetry run aca-py start --arg-file ./configs/alice.yml

  tunnel-bob:
    image: reflectivedevelopment/agent-tunnel
    command: agent-bob:3002 -p 4040 --host ${AGENT_TUNNEL_HOST}
  agent-bob:
    image: acapy-toolbox-tunnel
    build:
      context: ../
      dockerfile: ./demo/Dockerfile.demo
    environment:
      TUNNEL_HOST: tunnel-bob
      TUNNEL_PORT: 4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3003:3003"
    command: poetry run aca-py start --arg-file ./configs/bob.yml

  # tunnel-tails-server:
  #   image: efrecon/localtunnel
  #   restart: on-failure
  #   links:
  #     - tails-server
  #   depends_on:
  #     - tails-server
  #   command: --local-host tails-server --port 6543 --host ${TAILS_TUNNEL_HOST:-https://localtunnel.me}
  # tails-server:
  #   image: dbluhm/indy-tails-server:latest
  #   ports:
  #     - 6543:6543
  #   command: >
  #     tails-server
  #       --host 0.0.0.0
  #       --port 6543
  #       --storage-path ${STORAGE_PATH:-/tmp/tails-files}
  #       --log-level ${LOG_LEVEL:-INFO}
